// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace IndexLessNamespace {
  export interface IIndexLess {
    "installation-view": string;
  }
}

declare const IndexLessModule: IndexLessNamespace.IIndexLess;

export = IndexLessModule;
